# Generated by Django 4.1.2 on 2022-10-18 18:57

import autocompletes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('land', autocompletes.models.ManyToManyField(to='autocompletes.land')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('bio', models.BooleanField(blank=True, default=True, verbose_name='Allow BIO products')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocompletes.land')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('visibile', models.BooleanField(blank=True, default=True, verbose_name='Visible')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocompletes.product')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocompletes.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=autocompletes.models.ManyToManyField(limit_choices_to=models.Q(('bio', True)), to='autocompletes.region'),
        ),
    ]
